#:import utils kivy.utils

<Button>
  font_size: 20
  size_hint: None, None
  height: 40
  width: 140

<MainLayout>
  BoxLayout:
    size: root.width, root.height
    orientation: 'vertical'

    Label:
      id: name_label
      text: "What's your name?"
      font_size: 32

    TextInput:
      id: name_input
      multiline: False
      size_hint: 1, .5
      font_size: 20

    Button:
      text: "Submit"
      size_hint: 1, 0.5
      font_size: 32
      on_press: root.press()


    