

<MainLayout>

  BoxLayout:
    orientation: 'vertical'
    size: root.width, root.height
    padding: 20
    spacing: 20

    Button:
      text: 'Butt1'

    Button:
      text: 'Butt2'

    Button:
      text: 'Butt3'
      pos_hint: {'center_x': 0.5,'center_y': 0.0} #Положение
      size_hint: 0.5, None # Относительный размер, ставим оба на None если хотим задать абсолютный размер
      height: 40