#:import utils kivy.utils

<Button>
  font_size: 32
  background_normal: ''
  background_color: utils.get_color_from_hex('#40d8b5')
  color: utils.get_color_from_hex('#304d46')

<MainLayout>
  BoxLayout:
    orientation: 'vertical'
    size: root.width, root.height
    padding: 10
    spacing: 10

    Image:
      source: '../data/images/poker.png'
      allow_stretch: True
      keep_ratio: False